baseurl = "https://samuelhorovatin.com"
disqusShortname = "shorovatin"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  author = "Samuel Horovatin"
  description = "Samuel Horovatins personal website"
  info = "Developer, Bioinformatician, and Dinosaur/Fish Enthusiast"
  avatarurl = "img/headshot_low.png"
  footercontent = "When something is important enough, you do it even if the odds are not in your favor." 
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "SamuelHorovatin"
    keywords = "blog,developer,bioinformatics,personal,Horovatin"
    copyright = "© 2020 Samuel Horovatin"
    menuMore = "Show more"
    readMore = "Read more"

    [languages.en.params.logo]
      logoText = "Samuel Horovatin"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/syncrotron"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://ca.linkedin.com/in/sam-horovatin-0b31a0103"
